### ISSUE TITLE
Question: what is the benefit of customising the webpack Terser plugin ?

### ISSUE THREAD

**Issue by decebal** [s4nt14go/white-label#1]
Code Reference:
https://github.com/s4nt14go/white-label/blob/master/webpack.config.js#L37

**Comment by s4nt14go** [comment]
Thanks for asking Decebal! If we prevent Webpack from minifying the classes names',  once we get an error we'll know in which class the error happened by looking into the error stack trace (also, at certain lines, we're logging some classes constructor names and it would show the minified version if we don't use the plugin)
